import { db } from "@/lib/db";
import { requireRole } from "@/lib/auth";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { EmptyReportsState } from "@/components/ui/empty-state";
import { Calendar } from "lucide-react";
import { format } from "date-fns";
import { GenerateReportButton, ReportExportButton, ReportShareButton } from "@/components/report-actions";

export default async function Reports() {
  const user = await requireRole(["ADMIN", "ANALYST", "VIEWER"]);

  const reports = await db.report.findMany({
    where: { workspaceId: user.workspaceId, deletedAt: null },
    orderBy: { createdAt: "desc" },
    include: {
      author: {
        select: { name: true, email: true }
      }
    }
  });

  const canCreate = user.role === "ADMIN" || user.role === "ANALYST";

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col items-start justify-between gap-4 animate-slide-up sm:flex-row sm:items-center">
        <div>
          <div className="mb-2 inline-flex items-center gap-2 rounded-full border border-violet-100 bg-violet-50 px-3 py-1 text-xs font-medium text-violet-700">
            <span className="h-1.5 w-1.5 rounded-full bg-violet-500" />
            Executive intelligence
          </div>
          <h1 className="text-3xl font-semibold tracking-tight text-slate-900">Voice of Customer Reports</h1>
          <p className="mt-1 text-slate-500">Saved leadership-ready summaries and insights</p>
        </div>
        {canCreate && (
          <GenerateReportButton />
        )}
      </div>

      {/* Reports Grid */}
      {reports.length === 0 ? (
        <Card className="animate-slide-up stagger-1">
          <CardContent className="p-12">
            <EmptyReportsState canCreate={canCreate} />
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-4 animate-slide-up stagger-1">
          {reports.map((report) => {
            const summary = (report.contentJson ?? {}) as Record<string, any>;

            return (
              <div id={report.id} key={report.id} className="scroll-mt-6">
              <Card className="hover-lift overflow-hidden">
                <CardHeader className="bg-gradient-to-br from-white to-violet-50/40">
                  <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                    <div className="min-w-0 flex-1">
                      <div className="flex flex-wrap items-center gap-3 mb-2">
                        <h3 className="text-lg font-medium text-slate-900">{report.title}</h3>
                        <Badge variant="default">VoC Report</Badge>
                      </div>
                      <div className="flex flex-wrap items-center gap-x-4 gap-y-2 text-sm text-slate-500">
                        <div className="flex items-center gap-1">
                          <Calendar className="w-4 h-4" />
                          <span>
                            {format(new Date(report.periodStart), "MMM d, yyyy")} — {format(new Date(report.periodEnd), "MMM d, yyyy")}
                          </span>
                        </div>
                        <div>•</div>
                        <div>Generated by {report.author.name}</div>
                      </div>
                    </div>
                    <div className="flex shrink-0 flex-wrap gap-2">
                      <ReportExportButton reportId={report.id} title={report.title} summary={JSON.stringify(summary, null, 2)} />
                      <ReportShareButton reportId={report.id} title={report.title} />
                    </div>
                  </div>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    {/* Report Summary */}
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                      <ReportStat
                        label="Top Themes"
                        value={summary.topThemes?.length || 0}
                        icon="🎯"
                      />
                      <ReportStat
                        label="Sentiment Shift"
                        value={summary.sentimentShift || "N/A"}
                        icon="📊"
                      />
                      <ReportStat
                        label="Actions"
                        value={summary.recommendedActions?.length || 0}
                        icon="✅"
                      />
                    </div>

                    {/* Key Insights */}
                    {summary.quotes && summary.quotes.length > 0 && (
                      <div>
                        <h4 className="text-sm font-semibold text-slate-900 mb-2">Key Customer Quotes</h4>
                        <div className="space-y-2">
                          {summary.quotes.slice(0, 2).map((quote: string, index: number) => (
                            <div key={index} className="p-3 bg-slate-50 rounded-lg text-sm text-slate-700 italic">
                              &quot;{quote}&quot;
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Recommended Actions */}
                    {summary.recommendedActions && summary.recommendedActions.length > 0 && (
                      <div>
                        <h4 className="text-sm font-semibold text-slate-900 mb-2">Recommended Actions</h4>
                        <div className="space-y-2">
                          {summary.recommendedActions.map((action: string, index: number) => (
                            <div key={index} className="flex items-start gap-2 text-sm">
                              <div className="w-5 h-5 rounded-full bg-green-100 flex items-center justify-center flex-shrink-0 mt-0.5">
                                <span className="text-green-600 text-xs">{index + 1}</span>
                              </div>
                              <span className="text-slate-700">{action}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                </CardContent>
              </Card>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

function ReportStat({ label, value, icon }: { label: string; value: string | number; icon: string }) {
  return (
    <div className="p-3 bg-slate-50 rounded-lg">
      <div className="flex items-center gap-2 mb-1">
        <span className="text-lg">{icon}</span>
        <span className="text-sm text-slate-600">{label}</span>
      </div>
      <div className="text-lg font-semibold text-slate-900">{value}</div>
    </div>
  );
}
